spring.application.name=bidmart-auth-service

server.port=${PORT:8081}

spring.datasource.url=${JDBC_DATABASE_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/auth_db}}
spring.datasource.username=${JDBC_DATABASE_USERNAME:${SPRING_DATASOURCE_USERNAME:auth}}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:${SPRING_DATASOURCE_PASSWORD:auth}}
spring.datasource.driver-class-name=org.postgresql.Driver

admin.bootstrap.enabled=${ADMIN_BOOTSTRAP_ENABLED:false}
admin.bootstrap.username=${ADMIN_BOOTSTRAP_USERNAME:}
admin.bootstrap.password=${ADMIN_BOOTSTRAP_PASSWORD:}

spring.sql.init.mode=always

auth.access-ttl-minutes=${AUTH_ACCESS_TTL_MINUTES:${JWT_ACCESS_TOKEN_TTL_MINUTES:15}}
auth.refresh-ttl-days=14
auth.max-sessions-per-user=5
auth.overflow-policy=REVOKE_OLDEST

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME:}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

auth.demo-static-codes-enabled=true
auth.demo-email-verification-code=112233
auth.demo-email-otp-code=445566

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

auth.captcha-enabled=true
auth.captcha-ttl-seconds=180
auth.captcha-length=5
auth.captcha-noise-lines=5
auth.captcha-case-sensitive=true

# Untuk komunikasi antar repo dengan JWT
jwt.issuer=${JWT_ISSUER:http://localhost:8081}
jwt.key-id=${JWT_KEY_ID:bidmart-auth-key-1}
jwt.access-token-ttl-minutes=${JWT_ACCESS_TOKEN_TTL_MINUTES:15}
jwt.private-key-base64=${JWT_PRIVATE_KEY_BASE64:}
jwt.public-key-base64=${JWT_PUBLIC_KEY_BASE64:}
auth.grpc.port=${AUTH_GRPC_PORT:9091}
auth.grpc.enabled=${AUTH_GRPC_ENABLED:true}
